### ISSUE TITLE
Redcap v7.4.9 - receiving KeyError on p = Project(url, key)

### ISSUE THREAD

**Issue by Celerrime** [redcap-tools/PyCap#79]
I've verified that my key works with the following code

```
from requests import post
# Two constants we'll use throughout
TOKEN = 'SECRET_KEY'
URL = 'https://redcap.vanderbilt.edu/api/'

payload = {'token': TOKEN, 'format': 'json', 'content': 'metadata'}

response = post(URL, data=payload)
print response.status_code
200
```

However, I'm receiving a KeyError when trying to instantiate the Project object. Can you confirm if PyCap has been tested for REDCap version >= 7.4.9?

```
>>> from redcap import Project
>>> url = 'https://redcapproduction.example.com/api/'
>>> key = 'API_KEY'
>>> p = Project(url, key)
/miniconda3/envs/redcap-env/lib/python3.6/site-packages/redcap/project.py:107: UserWarning: Version information not available for this REDCap instance
  warnings.warn('Version information not available for this REDCap instance')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/redcap-env/lib/python3.6/site-packages/redcap/project.py", line 53, in __init__
    self.configure()
  File "/miniconda3/envs/redcap-env/lib/python3.6/site-packages/redcap/project.py", line 64, in configure
    self.field_names = self.filter_metadata('field_name')
  File "/miniconda3/envs/redcap-env/lib/python3.6/site-packages/redcap/project.py", line 142, in filter_metadata
    raise KeyError("Key not found in metadata")
KeyError: 'Key not found in metadata'
```

**Comment by sburns** [comment]
I have definitely not tested on 7.4.9. Can you try to `Project(url, key, lazy=True)` and see if that helps? However, I think it will only delay the issue. It appears as though they've changed the structure of the project metadata returned in the API.

**Comment by Celerrime** [comment]
Issue was on my end. Was able to resolve using a corrected URL and lazy=True.
